config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
  

  resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emergency.rb
class Emergency < ApplicationRecord
    
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    
    before_save { self.email = self.email.downcase }
    validates :name, presence: true, length: {maximum: 50 }
    VALID_RMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_RMAIL_REGEX},
    uniqueness: {case_sensitive: false}
    
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @Title = "Stock Datas"
    @datas = Stock.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Laplusmembers!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
    
    #株価表示
    @Title = "Stock Datas"
    @datas = Stock.where(code: @user)
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attribute(:status,  params[:status])
      redirect_to @user, notice: '取引ステータスを更新しました。'
    else
      render 'show'
    end
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/
#{gravatar_id}
?s=
#{size}
"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<!--
<footer class="navbar navbar-fixed-bottom navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <span>&copy; 2017 LAplus.TECH, Inc</span>
        <li><a href="#">利用規約</a></li>
        <li><a href="#">プライバシーポリシー</a></li>
        <li> <a href="#">ヘルプ</a></li>
      </ul>
    </nav>
  </div>
</footer>
-->

<footer class="footer">
  <div class="container">
    <span class="text-muted">&copy; 2017 LAplus.TECH, Inc</span>
    <a href="#">利用規約</a>
    <a href="#">プライバシーポリシー</a>
    <a href="#">ヘルプ</a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "LAplus", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", '#' %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", logout_path, method: :destroy %>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LAplus.TECH</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %> <!-- ここから -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> <!-- ここまで追加 -->
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

<div id = "error_explanation">
    <div class = "alert alert-danger">
        The form contains
        <%= pluralize(object.errors.count, "error") %>
        .
        
    </div>
    <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li>
            <%= msg %>
        </li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/static_pages/home.html.erb
<style>/*<!--
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>LAplus.TECH</title>
-->

        <!-- BootstrapのCSS読み込み -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <!-- jQuery読み込み -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- BootstrapのJS読み込み -->
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        
        <!--
            <link rel = "stylesheet" href = "home.css">
            <link rel = "shortcut icon" href = "fabicon.ico">
        -->
        
        
    </head>
*/</style>
        <div class = "first_message">
            <h1>LAplus.TECH</h1>
            <h2>For Life Asisting...</h2>
        </div>
        <section>
            
        </section>
        
        <article>
            <hr>
            <div class = "container">
                <h1>Stock Datas</h1>
                <div class = "table-responsive">
                    <table class = "table table-bordered">
                        <thead>
                            <tr>
                                <th>コード</th>
                                <th>銘柄</th>
                                <th>株価</th>
                                <th>前日比</th>
                                <th>取引</th>
                                <th>取引単位</th>
                                <th>保有株数</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @datas.each do |data| %>
                                <tr>
                                    <td><%= data.code %></td>
                                    <td><%= data.bn %></td>
                                    <td><%= data.sp %></td>
                                    <td><%= data.dbr %></td>
                                    <td><%= data.tr %></td>
                                    <td><%= data.tru %></td>
                                    <td><%= data.nsh %></td>
                                </tr>
                                
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </article>    
        
<!--
    </body>
</html>
-->

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
<%= form_for(@user) do |f| %>

<%= render 'shared/error_messages', object: f.object %>
      
<%= f.label :name %>

      
<%= f.text_field :name, class: 'form-control' %>


      
<%= f.label :email %>

      
<%= f.text_field :email, class: 'form-control' %>


      
<%= f.label :password %>

<%= f.password_field :password, class: 'form-control' %>


      
<%= f.label :password_confirmation, "Confirmation" %>

      
<%= f.password_field :password_confirmation, class: 'form-control' %>


      
<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>

    
<% end %>


  </div>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap Sample</title>
        <!-- BootstrapのCSS読み込み -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <!-- jQuery読み込み -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- BootstrapのJS読み込み -->
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>

    <body>
        <!-- ここから　-->
        <h1>
        <%= gravatar_for @user %>
    
        <%= @user.name %>
        <!-- ここまで　-->
        <div class="btn-group">
	        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
		        取引ステータス変更
		        <span class="caret"></span>
	        </button>
	        <ul class="dropdown-menu" role="menu">
		        <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= button_to '通常取引', user_path(@user), method: :put, params: {status: '0'} %></a></li>
		        <li role="presentation"><%= button_to '売り停止', user_path(@user), method: :put, params: {status: '1'} %></li>
		        <li role="presentation"><%= button_to '売買停止', user_path(@user), method: :put, params: {status: '2'} %></li>
		        <li role="presentation"><%= button_to '全株放棄', user_path(@user), method: :put, params: {status: '3'} %></li>
	        </ul>
        </div>
        
        <%= "Stock Datas" %>
    
        </h1>
        <div class = "container">
            <div class = "table-responsive">
                <table class = "table table-bordered">
                    <thead>
                        <tr>
                            <th>コード</th>
                            <th>銘柄</th>
                            <th>株価</th>
                            <th>前日比</th>
                            <th>取引</th>
                            <th>取引単位</th>
                            <th>保有株数</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @datas.each do |data| %>
                            <tr>
                                <td><%= data.code %></td>
                                <td><%= data.bn %></td>
                                <td><%= data.sp %></td>
                                <td><%= data.dbr %></td>
                                <td><%= data.tr %></td>
                                <td><%= data.tru %></td>
                                <td><%= data.nsh %></td>
                            </tr>
                            
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>